const environmentVariables = {
  STG02_AUTH_URL: Cypress.env('STG02_AUTH_URL'),
  MFA_STG02_ACCOUNT_ID: Cypress.env('MFA_STG02_ACCOUNT_ID'),
  MFA_STG02_USER_EMAIL: Cypress.env('MFA_STG02_USER_EMAIL'),
  MFA_STG02_USER_PASSWORD: Cypress.env('MFA_STG02_USER_PASSWORD'),
  STG02_OKTA_LOGIN_URL: Cypress.env('STG02_OKTA_LOGIN_URL'),
  MFA_STG02_NON_FEDERATED_EMAIL: Cypress.env('MFA_STG02_NON_FEDERATED_EMAIL'),
  IDV2_FEDERATED_USERNAME: Cypress.env('IDV2_FEDERATED_USERNAME'),
  IDV2_FEDERATED_PASSWORD: Cypress.env('IDV2_FEDERATED_PASSWORD'),
};

export default environmentVariables;
